version: "3"
services:
  backend-s:
    build: ./health_predictor_tornado_app
    image: swarooppadala/ckdbackend
    ports: 
      - "80:8080"
    expose:
      - "80"
  frontend-s:
    build: ./ckd-angular-app
    image: swarooppadala/ckdfrontend
    ports: 
      - "4200:80"
    expose: 
      - "80"
    links:
      - backend-s
    depends_on:
      - backend-s